import { NormalizedTrial } from "../models/NormalizedTrial";

export function makeTrial(overrides: Partial<NormalizedTrial> = {}): NormalizedTrial {
    return {
        nctId: "NCT00000001",
        briefTitle: "Test Trial",
        officialTitle: null,
        acronym: null,
        phase: "PHASE2",
        studyType: "INTERVENTIONAL",
        overallStatus: "COMPLETED",
        whyStopped: null,
        hasResults: false,
        enrollmentCount: 100,
        enrollmentType: "ACTUAL",
        startDate: "2020-01",
        completionDate: "2022-01",
        allocation: "RANDOMIZED",
        interventionModel: "PARALLEL",
        primaryPurpose: "TREATMENT",
        masking: "DOUBLE",
        whoMasked: ["PARTICIPANT", "INVESTIGATOR"],
        armCount: 2,
        conditions: ["Diabetes"],
        interventions: ["Drug X"],
        interventionTypes: ["DRUG"],
        eligibilityCriteria: "Inclusion Criteria:\n* Adults 18-65.\nExclusion Criteria:\n* Pregnancy.",
        sex: "ALL",
        minimumAge: "18 Years",
        maximumAge: "65 Years",
        healthyVolunteers: false,
        stdAges: ["ADULT"],
        primaryOutcomes: [],
        secondaryOutcomes: [],
        sponsor: null,
        sponsorClass: null,
        collaboratorCount: 0,
        locationCount: 0,
        countries: [],
        hasDmc: null,
        meshTerms: [],
        ...overrides,
    };
}